### ISSUE TITLE
no main manifest attribute, in spock-example-1.0.jar

### ISSUE THREAD

**Issue by kamal2222ahmed** [spockframework/spock-example#13]
i am trying to run the tests as one jar, by adding the following in build.gradle

apply plugin: 'application'

```
task uberJar(type: Jar,dependsOn:[':compileGroovy']) {
    zip64 true
    from files(sourceSets.main.output.classesDir)
    from configurations.runtime.asFileTree.files.collect {zipTree(it) }
    with jar
}
```

but when i run it as java -jar spock-example-1.0.jar

i get error:

no main manifest attribute, in spock-example-1.0.jar

is it because there is no main() entry point in the jar ? if not then how can i run it ? 
either via command line, or gradle, since it seems in order to run a jar via gradle, there needs to be a main(), but groovy files do not have main() hence the confusion

**Comment by leonard84** [comment]
The project is not designed as a standalone test runner. It relies on gradle or maven to do that work. If you want to create a self contained jar, then you need to look into the JUnit Core Runner class, but it will not be out of the box.
