### ISSUE TITLE
The input type of the launch configuration does not exist - eclipse

### ISSUE THREAD

**Issue by kstojanovski** [spockframework/spock-example#14]
Hallo spock-example contributors,

cloning the project and exectuing it on eclipse I got the error: 

> The input type of the launch configuration does not exist

but only when the test cases are executed separately as JUnits.

One fix is to rename the file or the name of the class, i.e.; 
- PublisherSubscriberSpec.groovy -> PublisherSpec.groovy
- SpecInheritanceSpec.groovy -> DerivedSpec.groovy 

Then to split the test cases of StackSpec.groovy into seprate files i.e:
- class EmptyStackSpec -> EmptyStackSpec.groovy
- class StackWithOneElementSpec -> StackWithOneElementSpec.groovy
- class StackWithThreeElementsSpec -> StackWithThreeElementsSpec.groovy

Best Regards,
Kosta

**Comment by leonard84** [comment]
This is/was an eclipse issue it works fine in Intellij, this example project should showcase the possibilities so I'll leave it as it is.

**Comment by gsinghab2** [comment]
Opened eclipse defect https://bugs.eclipse.org/bugs/show_bug.cgi?id=548474

Also a simple workaround is to rename the PublisherSpec class in PublisherSubscriberSpec.groovy to PublisherSubscriberSpec.

**Comment by chintohere** [comment]
🐒
