### ISSUE TITLE
Test sources not recognised by IDEA after Maven (re-)import

### ISSUE THREAD

**Issue by kriegaex** [spockframework/spock-example#24]
I have my own Maven setup for Spock/Geb and when importing projects using that setup, IDEA automatically recognises Spock tests under `src/test/groovy` or `src/test/java`. Now I wanted to use your repository just because I was curious. I did not import the Gradle but the Maven project and the Spock specs are all imported as Groovy scripts only, the test folder is not recognised unless I manually mark it as such in the project settings. But with Maven auto-import active, whenever I change something in the POM, the setting is gone again.

Please fix your Maven project so as to enable auto-import from IDEA.

**Comment by leonard84** [comment]
You need to have this plugin installed, there is nothing wrong with this project.
* https://github.com/mycila/gmavenplus-intellij-plugin
* https://plugins.jetbrains.com/plugin/7442-gmavenplus-intellij-plugin

**Comment by kriegaex** [comment]
How could I have known, the read-me page did not mention it until after I opened this ticket. But thanks for adding the information now, it will help future users. :-)

Besides, my own setup does not require any IDEA plugin in order to correctly recognise the test classes. It is not based based on GMaven+ but on using Groovy Eclipse Compiler via `<compilerId>` from Maven Compiler. If you are interested in migrating this project, let me know. I can provide code snippets or full projects.

**Comment by leonard84** [comment]
The Groovy Eclipse Compiler does not always produce the same result as the native groovy compiler does, that is why we prefer to use gmaven+. I too find it annoying that IDEA does not recognize the groovy sources by default, but maybe that should be an issue in the IDEA Bugtracker.

> There is also no need to generate an IDEA project via Maven first, I just import the POM and that's it. 

It should work the same with this project.
