### ISSUE TITLE
Setting Spock config file in static block does not work in IncludeExcludeExtensionSpec

### ISSUE THREAD

**Issue by kriegaex** [spockframework/spock-example#25]
https://github.com/spockframework/spock-example/blob/fb70660652e22f2c51e3affb0bc23ab96202dae2/src/test/groovy/IncludeExcludeExtensionSpec.groovy#L42

I ran the test from both Maven and IDEA, but the property is not picked up unless I set it from outside. Always all three feature methods get executed. I assume that setting the property in the static class initialiser is too late in Spock's lifecycle to be picked up before the decision is made which tests to execute.

**Comment by leonard84** [comment]
Please see the accompanying comment, that states that this is just for "demonstration purposes". 

> Shows how methods can be included and excluded from a spec run. For
> demonstration purposes, the configuration script's location is set
> programmatically in a static initializer. Usually, the configuration
> script's location would be set externally (via the same system property),
> or the configuration script would reside in one of the two default locations:
> * `SpockConfig.groovy` on the class path
> * `$user_home/.spock/SpockConfig.groovy` on the file system
>
> Note that the configuration script referenced by the system property
> may either reside on the class path or on the file system (make sure to
> include the whole path).
>
> What's not shown here is that filtering also works for classes.
> Whereas methods can only be filtered based on annotations, classes can
> also be filtered based on their base class.

**Comment by kriegaex** [comment]
I read everything before opening the ticket. The term "for demonstration purposes" to me means that you demonstrate something which really works. In fact, it does not and the tests always run. I suggest to demonstrate this in a different way or from a different place which actually works. Minimally, please mention explicitly that setting the value in a static block does NOT work. Why use a sophisticated aporoach like a static initialiser and explicitly setting system properties therein if it is completely pointless? I would not have opened this or any of my other recent tickets if the tests spoke for themselves. I am fairly experienced in both Geb and Spock and I also know how to read, which I usually do before asking questions.
