### ISSUE TITLE
Mvn clean install on spock-example provokes a TestNG error message

### ISSUE THREAD

**Issue by rodrigo-ottero** [spockframework/spock-example#30]
Hi all,

I cloned the spock-example project and got this message when running `mvn clean install`:

> [INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[TestNG] [ERROR] No test suite found. Nothing to run
Usage: <main class> [options] The XML suite files to run
  Options:
    -configfailurepolicy
      Configuration failure policy (skip or continue)
    -d
      Output directory
    -dataproviderthreadcount
      Number of threads to use when running data providers
...

After this message, the Spock tests run as expected.

Kind regards,

Rodrigo

**Comment by rodrigo-ottero** [comment]
I did some investigation on the issue, it seems the cause is the underlying provider maven-surefire is using, in this case TestNG. 

As per [surefire documentation](http://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html):

> Surefire normally automatically selects which test-framework provider to use based on the version of TestNG/JUnit present in your project's classpath.

I managed to solve the problem for my local install by specifying junit as the provider:

`      <plugin>`
`        <artifactId>maven-surefire-plugin</artifactId>`
`        <version>3.0.0-M3</version>`
`        <configuration>`
`          <useFile>false</useFile>`
`          <includes>`
`            <include>**/*Test.java</include>`
`            <include>**/*Spec.java</include>`
`          </includes>`
`        </configuration>`
`        <dependencies>`
`          <dependency>`
`            <groupId>org.apache.maven.surefire</groupId>`
`            <artifactId>surefire-junit47</artifactId>`
`            <version>3.0.0-M3</version>`
`          </dependency>`
`        </dependencies>`
`      </plugin>`

This was the result:

![image](https://user-images.githubusercontent.com/15771977/60011865-9dd60d80-9672-11e9-8dfc-68ecf02cf873.png)

Sharing this in case it is helpful.

Kind regards

**Comment by leonard84** [comment]
This should be fixed in the current master, furthermore don't use `groovy-all` as surefire gets confused by `groovy-testng`.
