### ISSUE TITLE
Surefire plugin configuration targets .java file extension?

### ISSUE THREAD

**Issue by umutcanbolat** [spockframework/spock-example#41]
In the pom.xml, the surefire plugin configuration targets `.java` file extension, even though the tests are written in `.groovy` files.

Is this configuration correct?
https://github.com/spockframework/spock-example/blob/master/pom.xml#L43-L44

**Comment by leonard84** [comment]
Both with and without extension work, and the `.java` was even required back in the day [2005](https://solidsoft.wordpress.com/2015/03/09/spock-1-0-with-groovy-2-4-configuration-comparison-in-maven-and-gradle/), nevertheless I've updated it so it is less confusing.
