### ISSUE TITLE
Shouldn't use GMaven in Maven example

### ISSUE THREAD

**Issue by keeganwitt** [spockframework/spock-example#7]
GMaven doesn't work with newer Groovy versions.  One example is that it's impossible for GMaven to compile Groovy classes that use traits.  The last GMaven update I did was to make the 2.0 provider use Groovy 2.0.1, so really GMaven should not be used beyond the 2.0.x line.  I (and [others](https://twitter.com/glaforge/status/473562903849996288)) recommend [GMavenPlus](https://github.com/groovy/GMavenPlus), but [Groovy-Eclipse](http://groovy-lang.org/groovyc.html#section-groovyeclipse) would work for those who don't need things like invokedynamic.  I've tried to give a neutral overview of the options (including non-Maven options) [here](https://github.com/groovy/GMavenPlus/wiki/Choosing-Your-Build-Tool).

**Comment by pniederw** [comment]
Thanks for the notice. I've updated the Maven build accordingly.
